# -*- coding: utf-8 -*-
"""2june2026Pythonday1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sAdRZejGUTsl9pPnM-6U25JIAZVXeQiz
"""

print ("Hello World")

a = 5
v = 10
b = 20
n = 25
k = 30
c = a + v + b + n + k
print(c)

a = int (input())
b = int (input())
c = int (input())
d = int (input())
e = int (input())
print (a+b+c+d+e)

a = int (input())
b = int (input())
c = int (input())
d = int (input())
e = int (input())
print (a+b+c+d+e)

"""if we dont give data type while taking input due to concatination it prints string directly not the sum oof the numbers

The error ValueError: invalid literal for int() with base 10: '5*10^9' means that the program tried to convert the text '5*10^9' into a whole number, but it couldn't. The int() function expects a string that looks like a number, not a mathematical expression. If you meant to input the value of 5 multiplied by 10 to the power of 9, you should input the numerical result directly, for example, '5000000000'.

not to use predefine words like sum as its a keyword we cant use as variable
"""

a = 5
b = 8
print (a)
print (b)
a = b
b = a
print(a)
print (b)

a = 5
b = 10

temp = a
a = b
b = temp

print("a =", a)
print("b =", b)

a = 3
b = 20

a, b = b, a

print("a =", a)
print("b =", b)

a = int (input())
b = int (input())
temp = a
a = b
b = temp

print("a =", a)
print("b =", b)

for i in range(1, 51):
    if i % 2 != 0:
        print(i)

for i in range(1, 51):
    if i % 2 == 0:
        print(i)

for i in range(1, 51):
    if i % 2 != 0:
        print("Odd is" ,i)
    else:
        print("Even is ",i)

a = int(input())
if a > 0 :
  print("positive")
elif a == 0 :
  print("zero")
else :
  print("negative")

a = str(input())

if a == "sun":
    print("Sunday")
elif a == "mon":
    print("Monday")
elif a == "tue":
    print("Tuesday")
elif a == "wed":
    print("Wednesday")
elif a == "thu":
    print("Thursday")
elif a == "fri":
    print("Friday")
elif a == "sat":
    print("Saturday")
else:
    print("Invalid day code")

for i in range (1 , 11 , 2):
 print (i)

for i in range (0 , 11 , 2):
 print (i)

a = 10
while a < 10 :
  print(a)

a = 0

while a < 10 :
  print (a)
  a = a+1

"""/ - decimal , // - integer value"""

#check palindrone
a = str(input())
if a == a[::-1]:
  print("palindrone")
else:
  print("not palindrone")